# Generated by Django 3.2.20 on 2023-10-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('room_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adult', models.IntegerField()),
                ('chield', models.IntegerField()),
                ('message', models.TextField()),
                ('owner', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('room_id', models.CharField(max_length=15)),
                ('floor', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('location', models.TextField()),
                ('about', models.TextField(null=True)),
                ('desc', models.TextField()),
                ('prize', models.IntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('updated_by', models.CharField(max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
